package com.treode.store

import com.treode.pickle.Picklers

object Fruits {

  // Thank you Wikipedia, http://simple.wikipedia.org/wiki/List_of_fruits
  val Apple = Bytes ("apple")
  val Apricot = Bytes ("apricot")
  val Avocado = Bytes ("avocado")
  val Banana = Bytes ("banana")
  val Bilberry = Bytes ("bilberry")
  val Blackberry = Bytes ("blackberry")
  val Blackcurrant = Bytes ("blackcurrant")
  val Blueberry = Bytes ("blueberry")
  val Boysenberry = Bytes ("boysenberry")
  val Breadfruit = Bytes ("breadfruit")
  val CanaryMelon  = Bytes ("canary melon")
  val Cantaloupe = Bytes ("cantaloupe")
  val Cherimoya = Bytes ("cherimoya")
  val Cherry = Bytes ("cherry")
  val Chili = Bytes ("chili")
  val Clementine = Bytes ("clementine")
  val Cloudberry = Bytes ("cloudberry")
  val Coconut = Bytes ("coconut")
  val Currant = Bytes ("currant")
  val Damson = Bytes ("damson")
  val Date = Bytes ("date")
  val Dragonfruit = Bytes ("dragonfruit")
  val Durian = Bytes ("durian")
  val Elderberry = Bytes ("elderberry")
  val Feijoa = Bytes ("feijoa")
  val Fig = Bytes ("fig")
  val Gooseberry = Bytes ("gooseberry")
  val Grape = Bytes ("grape")
  val Grapefruit = Bytes ("grapefruit")
  val Guava = Bytes ("guava")
  val Honeydew = Bytes ("honeydew")
  val Huckleberry = Bytes ("huckleberry")
  val Jackfruit = Bytes ("jackfruit")
  val Jambul = Bytes ("jambul")
  val Jettamelon = Bytes ("jettamelon")
  val Jujube = Bytes ("jujube")
  val Kiwi = Bytes ("kiwi")
  val Kumquat = Bytes ("kumquat")
  val Legume = Bytes ("legume")
  val Lemon = Bytes ("lemon")
  val Lime = Bytes ("lime")
  val Loquat = Bytes ("loquat")
  val Lychee = Bytes ("lychee")
  val Mandarine = Bytes ("mandarine")
  val Mango = Bytes ("mango")
  val Mangosteen = Bytes ("mangosteen")
  val Melon = Bytes ("melon")
  val Nectarine = Bytes ("nectarine")
  val Nut = Bytes ("nut")
  val Orange = Bytes ("orange")
  val Papaya = Bytes ("papaya")
  val Passionfruit = Bytes ("passionfruit")
  val Peach = Bytes ("peach")
  val Pear = Bytes ("pear")
  val Pepper = Bytes ("pepper")
  val Persimmon = Bytes ("persimmon")
  val Physalis = Bytes ("physalis")
  val Pineapple = Bytes ("pineapple")
  val Plum = Bytes ("plum")
  val Pomegranate = Bytes ("pomegranate")
  val Pomelo = Bytes ("pomelo")
  val Quince = Bytes ("quince")
  val Rambutan = Bytes ("rambutan")
  val Raspberry = Bytes ("raspberry")
  val Redcurrant = Bytes ("redcurrant")
  val RockMelon  = Bytes ("rock melon")
  val SalalBerry  = Bytes ("salal berry")
  val Satsuma = Bytes ("satsuma")
  val StarFruit  = Bytes ("star fruit")
  val Strawberry = Bytes ("strawberry")
  val Tamarillo = Bytes ("tamarillo")
  val Tangerine = Bytes ("tangerine")
  val Tomato = Bytes ("tomato")
  val UgliFruit  = Bytes ("ugli fruit")
  val Watermelon = Bytes ("watermelon")

  val AllFruits = Seq (Apple, Apricot, Avocado, Banana, Bilberry, Blackberry, Blackcurrant,
      Blueberry, Boysenberry, CanaryMelon, Cantaloupe, Cherimoya, Cherry, Chili, Clementine,
      Cloudberry, Coconut, Damson, Date, Dragonfruit, Durian, Elderberry, Feijoa, Fig, Gooseberry,
      Grape, Grapefruit, Honeydew, Huckleberry, Jackfruit, Jambul, Jettamelon, Jujube, Kiwi,
      Kumquat, Lemon, Lime, Loquat, Lychee, Mandarine, Mango, Mangosteen, Melon, Nectarine, Nut,
      Orange, Papaya, Passionfruit, Peach, Pear, Pepper, Persimmon, Physalis, Pineapple, Plum,
      Pomegranate, Pomelo, Quince, Rambutan, Raspberry, Redcurrant, RockMelon, SalalBerry, Satsuma,
      StarFruit, Strawberry, Tangerine, Tomato, UgliFruit, Watermelon)
}
